/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/RoleEditor.lh
 */
export class RoleEditorBase extends Laya.Box {
    public ComboBox!: Laya.ComboBox;
    public Label!: Laya.Label;
    public Tittle!: Laya.Label;
    public "Label(1)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(2)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(3)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(4)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(8)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(9)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(10)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(11)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(12)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(13)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(14)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(15)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    //public "Label(14)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    //public "Label(15)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    //public "Label(14)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    //public "Label(15)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    //public "Label(14)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    //public "Label(15)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    //public "Label(14)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    //public "Label(15)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    //public "Label(14)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    //public "Label(14)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    //public "Label(15)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(16)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(17)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(18)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(19)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(20)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(21)"!: Laya.Label;
    //public Tittle!: Laya.Label;
    public "Label(22)"!: Laya.Label;
    //public Tittle!: Laya.Label;
}

