/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Sprite.lh
 */
export class RuntimeScriptBase extends Laya.Sprite {
    public Label!: Laya.Label;
}

