/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { MyButton } from "./MyButton";

/**
 * Login.ls
 */
export class LoginBase extends Laya.Scene {
    public Button!: MyButton;
    public Sound!: MyButton;
}

