/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { MyButton } from "./MyButton";

/**
 * resources/prefab/PopUp.lh
 */
export class PopUpBase extends Laya.Sprite {
    public Label!: Laya.Label;
    public ok!: MyButton;
    public no!: MyButton;
}

