/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { MyButton } from "./MyButton";

/**
 * prefab/SkillTip.lh
 */
export class SkillTipBase extends Laya.Image {
    public Label!: Laya.Label;
    public ok!: MyButton;
    public no!: MyButton;
}

