/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { PopUp } from "../../ui/PopUp";
import { MyButton } from "../../ui/MyButton";

/**
 * Scene2.ls
 */
export class EndlessSceneBase extends Laya.Scene {
    public SkillTip!: PopUp;
    public label_1!: Laya.Label;
    public img_shuxing!: Laya.Image;
    public label_2!: Laya.Label;
    public btn_cuilian!: MyButton;
    public btn_jineng!: MyButton;
    public list_shuxing!: Laya.List;
    public img_jineng!: Laya.Image;
    public list_guyou!: Laya.List;
    public list_xuexi!: Laya.List;
    public btn_shuxing!: MyButton;
    public btn_login!: MyButton;
    public label_titile!: Laya.Label;
    public Map!: Laya.Sprite;
    public btn_tujian!: MyButton;
    public btn_jinhua!: MyButton;
    public btn_fanhui!: MyButton;
    public btn_sousuo!: MyButton;
    public btn_shenru!: MyButton;
    public btn_boss!: MyButton;
    public btn_zidong!: MyButton;
    public monster0!: MyButton;
    public monster1!: MyButton;
    public monster2!: MyButton;
    public player0!: MyButton;
    public Battle!: Laya.Sprite;
    public Player!: MyButton;
    public Enemy!: MyButton;
    public btn_taopao!: MyButton;
    public Damages!: Laya.Sprite;
    public List!: Laya.List;
    public Tujian!: PopUp;
    public Reward!: PopUp;
}

